#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Store-Summary
version:      1.0
version_from: Summary.pm
installdirs:  site
requires:
    Email::Store:                  0
    Text::Original:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
